### ISSUE TITLE
SoftDTW Divergence Loss for 3D data

### ISSUE THREAD

**Issue by denisbeslic** [google-research/soft-dtw-divergences#3]
Dear authors,

would it be possible to use the SoftDTW Divergence Loss for 3-dimensional data (batch_size, time series length, features)
e.g.,
```
# Two 3-dimensional time series of lengths 5 and 4, respectively.
X = np.random.randn(16, 5, 3)
Y = np.random.randn(16, 4, 3)
value = sdtw_div(X, Y, gamma=1.0)
```

Currently it does not work since it expects a 2-dimensional array. 
Is there a straight-forward way to adjust your code so that it works with 3d arrays?

Thanks for your help.

**Comment by mblondel** [comment]
We don't support a batch axis. You need to use a for loop.
